version: '3'

services:
  db:
    container_name: mongodb
    image: docker.uclv.cu/mongo
    restart: always
    env_file: ./peer/.env
    volumes:
      - mongo_data:/data/db

  peer:
    build: 
      context: .
      dockerfile: ./peer/Dockerfile
    depends_on: 
      - db
    ports:
      - 8080:8080
    volumes:
      - ./peer:/peer
    env_file: ./peer/.env

  api:
    build: 
      context: .
      dockerfile: ./api/Dockerfile
    depends_on: 
      - peer 
    volumes:
      - ./api:/api
    network_mode: host
  
  web:
    build:
      context: .
      dockerfile: ./client/Dockerfile
    depends_on:
      - api
    volumes:
      - ./client/src:/app/src
    ports:
      - 3000:3000

volumes:
  mongo_data:
