version: '3.9'

services:

  dns:
    build:
      context: ./dns
      dockerfile: Dockerfile
    # volumes:
    #   - ./dns:/dns
    stdin_open: true
    tty: true
    networks:
      - default

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    volumes:
      - ./web:/web
    stdin_open: true
    tty: true
    networks:
      - default

  api:
    build: 
      context: ./api
      dockerfile: Dockerfile
    # volumes:
    #   - ./api:/api
    stdin_open: true
    tty: true
    networks:
      - default

  peer:
    build: 
      context: ./peer
      dockerfile: Dockerfile
    # volumes:
    #   - ./peer:/peer
    stdin_open: true
    tty: true
    networks:
      - default
    depends_on:
      - db

  db:
    container_name: mongodb
    image: docker.uclv.cu/mongo
    restart: always
    env_file: ./peer/.env
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:

networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: 192.168.0.0/16
          gateway: 192.168.0.1
 
